apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  env: {{ .Values.env | quote }}
  debug: {{ .Values.debug | quote }}
  cors-allow-origin: {{ .Values.corsAllowOrigin | quote }}
  varnish-url: {{ if .Values.varnish.enabled }}http://varnish{{ else }}{{ .Values.varnish.url | quote }}{{ end }}
  trusted-hosts: {{ .Values.trustedHosts | quote }}
  trusted-proxies: {{ join "," .Values.trustedProxies }}
  mercure-acmeHosts: {{ .Values.mercure.acmeHosts | quote }}
  mercure-allowAnonymous: {{ .Values.mercure.allowAnonymous | quote }}
  mercure-corsAllowedOrigins: {{ .Values.mercure.corsAllowedOrigins | quote }}
  mercure-debug: {{ .Values.mercure.debug | quote }}
  mercure-demo: {{ .Values.mercure.demo | quote }}
  mercure-logFormat: {{ .Values.mercure.logFormat | quote }}
  mercure-publishAllowedOrigins: {{ .Values.mercure.publishAllowedOrigins | quote }}
