{{- if .Values.mercure.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}-mercure
  labels:
    app: {{ template "name" . }}-mercure
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.mercure.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-mercure
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-mercure
          image: "{{ .Values.mercure.image.repository }}:{{ .Values.mercure.image.tag }}"
          imagePullPolicy: {{ .Values.mercure.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: ACME_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: mercure-acmeHosts
            - name: ALLOW_ANONYMOUS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: mercure-allowAnonymous
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: mercure-corsAllowedOrigins
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: mercure-debug
            - name: DEMO
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: mercure-demo
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: mercure-jwtKey
            - name: LOG_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: mercure-logFormat
            - name: PUBLISH_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: mercure-publishAllowedOrigins
            - name: PUBLISHER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: mercure-publisherJwtKey
            - name: SUBSCRIBER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: mercure-subscriberJwtKey
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.mercure.resources | nindent 12 }}
      {{- with .Values.mercure.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.mercure.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.mercure.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
