language: php

php:
  - '7.4'

dist: trusty

services:
  - docker

cache:
  yarn: true
  directories:
    - admin/node_modules
    - client/node_modules

# The RELEASE is the name of the branch in lowercase, with slashes converted to dashes (i.e: feature/deploy => feature-deploy).
env:
  global:
    - BRANCH=$TRAVIS_BRANCH
    - RELEASE=`echo $BRANCH | sed -E "s/\//-/g" | sed -e 's/\(.*\)/\L\1/'`
    - NAMESPACE=$RELEASE

before_install:
  - source ci/.env
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - phpenv config-rm xdebug.ini
  - sudo service mysql stop
  - sudo service postgresql stop
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  - nvm install node
  - npm install -g react-scripts
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
  - ./ci/test

before_deploy:
  - source ci/before_deploy

# Create the travis service account access file from travis environment variables
# Connect to the project as travis service account by gcloud using the travis service account access file we just created above and configure project.
# Create the needed bucket in which to push builds.
# Deploy images and buckets according to the current context, create or update Kubenetes release with updated informations.
deploy:
  - provider: script
    script: bash ci/deploy
    skip_cleanup: true
    on:
      all_branches: true
      repo: api-platform/demo
