api_platform:
    title: API Platform's demo
    version: 1.0.0
    description: |
        This is a demo application of the [API Platform](https://api-platform.com) framework.
        [Its source code](https://github.com/api-platform/demo) includes various examples, check it out!
        You may also be interested by [the GraphQL entrypoint](/graphql).
        [A PWA](/) and [an admin](/admin) are consuming this API.
    graphql:
        graphql_playground: false
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
    mercure: ~
    http_cache:
        public: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    oauth:
        enabled: true
        clientId: '%env(OIDC_SWAGGER_CLIENT_ID)%'
        pkce: true
        type: oauth2
        flow: authorizationCode
        # todo retrieve url from .well-known
        tokenUrl: '%env(OIDC_SERVER_URL)%/protocol/openid-connect/token'
        # todo retrieve url from .well-known
        authorizationUrl: '%env(OIDC_SERVER_URL)%/protocol/openid-connect/auth'
        scopes:
            openid: (required) Indicates that the application intends to use OIDC to verify the user's identity

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    app.filter.review.admin.user:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments:
            $properties: { user: 'exact' } ]
        tags: [ 'api_platform.filter' ]

    app.filter.review.admin.book:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments:
            $properties: { book: 'exact' } ]
        tags: [ 'api_platform.filter' ]

    app.filter.review.admin.rating:
        parent: 'api_platform.doctrine.orm.numeric_filter'
        arguments:
            $properties: { rating: ~ } ]
        tags: [ 'api_platform.filter' ]

    # "name" is not a property, it's only a method "getName"
    # Can't apply ApiFilter PHP attribute on method, so declare filter manually
    app.filter.user.admin.name:
        class: 'App\Doctrine\Orm\Filter\NameFilter'
        arguments:
            $managerRegistry: '@doctrine'
            $logger: '@logger'
            $nameConverter: '@?api_platform.name_converter'
            $properties: { name: 'ipartial' } ]
        tags: [ 'api_platform.filter' ]
