api_platform:
    title: API Platform's demo
    version: 1.0.0
    description: |
        This is a demo application of the [API Platform](https://api-platform.com) framework.
        [Its source code](https://github.com/api-platform/demo) includes various examples, check it out!
        You may also be interested by [the GraphQL entrypoint](/graphql).
        [A PWA](/) and [an admin](/admin) are consuming this API.
    graphql:
        graphql_playground: false
    mercure: ~
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
    oauth:
        enabled: true
        clientId: '%env(OIDC_SWAGGER_CLIENT_ID)%'
        pkce: true
        type: oauth2
        flow: authorizationCode
        # todo retrieve url from .well-known
        tokenUrl: '%env(OIDC_SERVER_URL)%/protocol/openid-connect/token'
        # todo retrieve url from .well-known
        authorizationUrl: '%env(OIDC_SERVER_URL)%/protocol/openid-connect/auth'
        scopes:
            openid: (required) Indicates that the application intends to use OIDC to verify the user's identity

services:
    app.filter.review.admin.search:
        class: 'ApiPlatform\Doctrine\Orm\Filter\SearchFilter'
        arguments:
            $managerRegistry: '@doctrine'
            $iriConverter: '@api_platform.iri_converter'
            $propertyAccessor: '@property_accessor'
            $logger: '@logger'
            $properties: { user: 'exact', book: 'exact' } ]
            $identifiersExtractor: '@api_platform.api.identifiers_extractor'
            $nameConverter: '@?api_platform.name_converter'
        tags: [ 'api_platform.filter' ]

    app.filter.review.admin.numeric:
        class: 'ApiPlatform\Doctrine\Orm\Filter\NumericFilter'
        arguments:
            $managerRegistry: '@doctrine'
            $logger: '@logger'
            $properties: { rating: ~ } ]
            $nameConverter: '@?api_platform.name_converter'
        tags: [ 'api_platform.filter' ]
