name: Cleanup GitHub action for api-platform/demo
author: Vincent Chalamon <vincentchalamon@gmail.com>
description: Allow to cleanup api-platform/demo namespaces from Kubernetes
inputs:
  namespaces:
    required: true
    description: A list of namespaces to remove
  cf_api_token:
    required: true
    description: Cloudflare API Token
runs:
  using: composite
  steps:
    - shell: bash
      name: Download flarectl
      run: |-
        wget --no-check-certificate --content-disposition https://github.com/cloudflare/cloudflare-go/releases/download/v0.13.2/flarectl_0.13.2_linux_amd64.tar.xz
        tar -xf flarectl_0.13.2_linux_amd64.tar.xz flarectl
        chmod +x flarectl

    - shell: bash
      name: Remove Kubernetes namespace
      run: echo ${{ inputs.namespaces }} | xargs --no-run-if-empty kubectl delete namespace

    - shell: bash
      name: Remove Buckets
      run: |-
        echo ${{ inputs.namespaces }} | xargs --no-run-if-empty -n 1 -I {} gsutil -m rm -r gs://demo-admin-{}.api-platform.com
        echo ${{ inputs.namespaces }} | xargs --no-run-if-empty -n 1 -I {} gsutil -m rm -r gs://demo-client-{}.api-platform.com

    - shell: bash
      name: Remove Cloudflare domains
      env:
        CF_API_TOKEN: ${{ inputs.cf_api_token }}
      run: |-
        echo ${{ inputs.namespaces }} | xargs --no-run-if-empty -n 1 -I {} ./flarectl dns delete --zone=api-platform.com --id=demo-admin-{}.api-platform.com
        echo ${{ inputs.namespaces }} | xargs --no-run-if-empty -n 1 -I {} ./flarectl dns delete --zone=api-platform.com --id=demo-client-{}.api-platform.com
        echo ${{ inputs.namespaces }} | xargs --no-run-if-empty -n 1 -I {} ./flarectl dns delete --zone=api-platform.com --id=demo-mercure-{}.api-platform.com
        echo ${{ inputs.namespaces }} | xargs --no-run-if-empty -n 1 -I {} ./flarectl dns delete --zone=api-platform.com --id=demo-{}.api-platform.com
