# Check documentation at https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Cleanup

on:
  workflow_dispatch: ~
  schedule:
    - cron: '0 0 * * *'

env:
  GKE_CLUSTER: api-platform-demo
  GCE_ZONE: europe-west1-c
  DEFAULT_NAMESPACE: master
  MAX_LIFETIME: 4 days # Max lifetime for a namespace before being automatically deleted

jobs:
  remove-namespaces:
    name: Remove outdated and useless namespaces
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Get the GKE credentials so we can deploy to the cluster
      - run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GCE_ZONE }}

      # Remove all namespaces older than MAX_LIFETIME, except for DEFAULT_NAMESPACE
      - name: Get outdated namespaces
        id: outdated_ns
        run: echo "::set-output name=namespaces::$(kubectl get namespaces -l project=${{ env.GKE_CLUSTER }} --template '{{range .items}}{{.metadata.name}} {{.metadata.creationTimestamp}}{{"\n"}}{{end}}' | awk '$2 <= "'$(date -d 'now-${{ env.MAX_LIFETIME }}' -Ins --utc | sed 's/+0000/Z/')'" { print $1 }' | grep -v ${{ env.DEFAULT_NAMESPACE }})"

      - name: Remove outdated namespaces, buckets and domains
        uses: ./
        with: 
          namespaces: ${{ steps.outdated_ns.outputs.namespaces }}
          cf_api_token: ${{ secrets.CF_API_TOKEN }}

      # Remove all namespaces which branch don't exist anymore, except for DEFAULT_NAMESPACE
      - name: Get useless namespaces
        id: useless_ns
        run: echo "::set-output name=namespaces::$(diff <(kubectl get namespaces -l project=${{ env.GKE_CLUSTER }} --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}' | grep -v ${{ env.DEFAULT_NAMESPACE }}) <(git branch -r | grep -v origin/HEAD | grep -v ${{ env.DEFAULT_NAMESPACE }} | sed 's/^\s*origin\//feature-/' | sed 's/\//-/') | grep '<' | sed 's/< *//')"

      - name: Remove useless namespaces, buckets and domains
        uses: ./
        with:
          namespaces: ${{ steps.useless_ns.outputs.namespaces }}
          cf_api_token: ${{ secrets.CF_API_TOKEN }}
