# Check documentation at https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Tests

on:
  pull_request: ~
  workflow_dispatch: ~
  push:
    branches:
      - master

jobs:
  security-check:
    name: Security Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: curl, dom, iconv, intl, json, libxml, mbstring, phar, tokenizer, xdebug, xml, xmlwriter
          tools: symfony

      - name: Get Composer Cache Directory
        id: composer-cache
        working-directory: api
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        working-directory: api
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Security check
        working-directory: api
        run: symfony security:check

  doctrine-schema-validator:
    name: Doctrine Schema Validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: curl, dom, iconv, intl, json, libxml, mbstring, phar, tokenizer, xdebug, xml, xmlwriter

      - name: Get Composer Cache Directory
        id: composer-cache
        working-directory: api
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        working-directory: api
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Doctrine schema validator
        working-directory: api
        run: bin/console doctrine:schema:validate --skip-sync

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    env:
      COMPOSE_INTERACTIVE_NO_CLI: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker Compose stack
        run: |-
          docker-compose pull --ignore-pull-failures
          docker-compose build --pull
          docker-compose run php composer install -o -n
          docker-compose up -d

      - name: PHPUnit
        run: |-
          docker-compose exec -T php composer prepare-test-env
          docker-compose exec -T php composer tests

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    env:
      COMPOSE_INTERACTIVE_NO_CLI: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: curl, dom, iconv, intl, json, libxml, mbstring, phar, tokenizer, xdebug, xml, xmlwriter

      - name: Get Composer Cache Directory
        id: composer-cache
        working-directory: api
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        working-directory: api
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Install PHPUnit
        working-directory: api
        run: vendor/bin/simple-phpunit --version

      - name: PHPStan
        working-directory: api      
        run: |-
          composer symfony cache:warmup
          composer phpstan-analyse

  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta

      - name: Install dependencies
        working-directory: client
        run: yarn install --pure-lockfile

      - name: Jest
        working-directory: client
        run: yarn jest --ci --reporters=default --reporters=jest-junit --passWithNoTests

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta

      - name: Install dependencies
        working-directory: client
        run: yarn install --pure-lockfile

      - name: ESLint
        working-directory: client
        run: yarn eslint src

  helm-lint:
    name: Helm Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Helm
        run: helm lint ./api/helm/api/
